ChasseBundle\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        gender:
            type: string
            length: 10
        status:
            type: string
            length: 100
        age:
            type: smallint
        department:
            type: smallint
        newsletter:
            type: boolean
        satisfaction:
            type: tinyint


    oneToMany:
        interviews:
          targetEntity: Interview
          mappedBy: user