stats:
    path:     /statistiques-application
    defaults: { _controller: ChasseBundle:Back:stats }

userstats:
    path:     /statistiques-utilisateurs/{page}
    defaults: { _controller: ChasseBundle:Back:userStats }

winner:
    path:     /gagnant
    defaults: {_controller: ChasseBundle:Back:winner}