index:
    path:     /
    defaults: { _controller: ChasseBundle:Front:index }

howto:
    path:     /regles-du-jeu
    defaults: { _controller: ChasseBundle:Front:howto }

legalmention:
    path:     /mentions-legales
    defaults: { _controller: ChasseBundle:Front:legalmention }

countdown:
    path:     /countdown
    defaults: { _controller: ChasseBundle:Front:countDown }

votevalid:
    path:     /votevalid
    defaults: { _controller: ChasseBundle:Front:voteValid }