interview_index:
    path:     /
    defaults: { _controller: "ChasseBundle:Interview:index" }
    methods:  GET

interview_show:
    path:     /{id}/show
    defaults: { _controller: "ChasseBundle:Interview:show" }
    methods:  GET

interview_new:
    path:     /new
    defaults: { _controller: "ChasseBundle:Interview:new" }
    methods:  [GET, POST]

interview_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChasseBundle:Interview:edit" }
    methods:  [GET, POST]

interview_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChasseBundle:Interview:delete" }
    methods:  DELETE

job_choose:
    path:     /choose/{domain}
    defaults: { _controller: "ChasseBundle:Interview:jobchoose" }
    methods:  POST

job_select:
    path:     /select
    defaults: { _controller: "ChasseBundle:Interview:jobselect" }
    methods:  [GET, POST]

job_search:
    path:     /search/{word}
    defaults: { _controller: "ChasseBundle:Interview:jobsearch" }
    methods:  POST

job_searchhelp:
    path:     /searchhelp
    defaults: { _controller: "ChasseBundle:Interview:searchhelp" }
    methods:  POST